services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file: .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
